name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -e .[dev] || true

      - name: Run validation & tests (best-effort)
        run: |
          if [ -f data/nyc_taxi_curated.csv ]; then \
            python scripts/validate_curated.py --input data/nyc_taxi_curated.csv || true; \
          fi
          pytest -q || true
